import java.util.HashMap;

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1,2,3,5,8,13,21,34,55,89,…
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 *
 * E(n) = 4 * E(n-1) + E(n-2)
 *
 * as we know 1 and 2 we have initialised that,
 * start index is 3 because there is no value for E(-1) and E(0)
 *
 */
public class EvenFibonacciNumbers {

    private static HashMap<Integer, Integer> indexVsValue =  new HashMap<Integer, Integer>();

    static{
        indexVsValue.put( 1, 2 );
        indexVsValue.put( 2, 8 );
    }

    private static Integer startIndex = 3; //sum of even
    private static Integer sumOfEvenFibonacci = 0;

    public static Integer getValue(Integer index) {
        return indexVsValue.get(index);
    }

    public static void putIndexAndValue(Integer index, Integer value) {
        EvenFibonacciNumbers.indexVsValue.put(index, value);
    }

    public static Integer calculateTheSumEvenFiboncciNumbers(Integer max){
        if(max < 2){
            return max;
        }
        Integer nthEvenValue = null;

        do{
            nthEvenValue = ( 4 * valueOf( startIndex -1 ) + valueOf( startIndex - 2 ) );
            putIndexAndValue(startIndex, nthEvenValue);
            sumOfEvenFibonacci = sumOfEvenFibonacci + nthEvenValue;
            startIndex++;
        }while( sumOfEvenFibonacci < max);



        return sumOfEvenFibonacci;
    }

    private static int valueOf(int i) {
            return getValue(i);
    }

}
